# Site
title: Police Surveillance in Chicago
description: This intro to police surveillance technologies was produced from ongoing research through FOIA documents acquired by Lucy Parsons Labs as well as some public data
url: https://chicagopolicesurveillance.com
locale: en_US

# Left Block Images
background:
  homepage: images/LPL-Home1-glitchcrowd.gif # this image will be shown on homepage's left block
  post-list: images/pxlsrt-cpd-crp1.jpg             # this image will be shown on post list page
  default-post: images/pxlsrt-cpd-crp2.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /posts/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir: css
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
email:              info@lucyparsonslabs.com
twitter:            lucyparsonslabs
github:             lucyparsons


# Plugins (previously Gems)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
